#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x0A11B61D3657B901 (agordon@wi.mit.edu)
#
Name     : time
Version  : 1.9
Release  : 15
URL      : https://mirrors.kernel.org/gnu/time/time-1.9.tar.gz
Source0  : https://mirrors.kernel.org/gnu/time/time-1.9.tar.gz
Source1  : https://mirrors.kernel.org/gnu/time/time-1.9.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: time-bin = %{version}-%{release}
Requires: time-info = %{version}-%{release}
Requires: time-license = %{version}-%{release}

%description
`time' is a program that measures many of the CPU resources, such as
time and memory, that other programs use.  The GNU version can format
the output in arbitrary ways by using a printf-style format string to
include various resource measurements.  Some systems do not provide
much information about program resource use; `time' reports
unavailable information as zero values.

%package bin
Summary: bin components for the time package.
Group: Binaries
Requires: time-license = %{version}-%{release}

%description bin
bin components for the time package.


%package info
Summary: info components for the time package.
Group: Default

%description info
info components for the time package.


%package license
Summary: license components for the time package.
Group: Default

%description license
license components for the time package.


%prep
%setup -q -n time-1.9
cd %{_builddir}/time-1.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1605136641
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1605136641
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/time
cp %{_builddir}/time-1.9/COPYING %{buildroot}/usr/share/package-licenses/time/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/time

%files info
%defattr(0644,root,root,0755)
/usr/share/info/time.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/time/8624bcdae55baeef00cd11d5dfcfa60f68710a02
