#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x0A11B61D3657B901 (agordon@wi.mit.edu)
#
Name     : time
Version  : 1.9
Release  : 11
URL      : https://mirrors.kernel.org/gnu/time/time-1.9.tar.gz
Source0  : https://mirrors.kernel.org/gnu/time/time-1.9.tar.gz
Source99 : https://mirrors.kernel.org/gnu/time/time-1.9.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: time-bin
Requires: time-doc
BuildRequires : texinfo

%description
`time' is a program that measures many of the CPU resources, such as
time and memory, that other programs use.  The GNU version can format
the output in arbitrary ways by using a printf-style format string to
include various resource measurements.  Some systems do not provide
much information about program resource use; `time' reports
unavailable information as zero values.

%package bin
Summary: bin components for the time package.
Group: Binaries

%description bin
bin components for the time package.


%package doc
Summary: doc components for the time package.
Group: Documentation

%description doc
doc components for the time package.


%prep
%setup -q -n time-1.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522110298
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1522110298
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/time

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
